index:
    path: /
    controller: App\Controller\AppController::indexAction

peintures:
    path: /peintures
    controller: App\Controller\PeintureController::peintures

peinture_add:
    path: /peinture/add
    controller: App\Controller\PeintureController::create    

peinture_show:
    path: /peinture/show/{slug}
    controller: App\Controller\PeintureController::show

#peinture_edit:
#    path: /peinture/edit/{id}
#    controller: App\Controller\PeintureController::edit
#    requirements:
#    id: '\d+'

#peinture_delete:
#    path: /peinture/delete/{id}
#    controller: App\Controller\PeintureController::delete
#    requirements:
#    id: '\d+'

posts:
    path: /posts
    controller: App\Controller\PostController::posts

portfolio:
    path: /portfolio
    controller: App\Controller\PortfolioController::portfolio

portfolio_categorie:
    path: /portfolio/{slug}
    controller: App\Controller\PortfolioController::categorie

a_propos:
    path: /a_propos
    controller: App\Controller\AProposController::apropos
